### ISSUE TITLE
Update for Woocommerce 2.6.4

### ISSUE THREAD

**Issue by rsiero** [crazy2death/wc-split-order#1]
I've updated the code for use in the new versions of Woocommerce

In wc-pending-split-admin.js (/admin/js/) in row 85 i've replaced

$("#woocommerce-order-items .item").has('.check-column input:checked').each(function(index, el) {

with

$("#woocommerce-order-items .item.selected").each(function(index, el) {

because the checkboxes are gone...

**Comment by rchougui** [comment]
Hello @rsiero ,
This repository was created for educational purposes, it was completely unmaintained and owned by a different old account.
I found out about it today and transferred it to my current account.
I plan to maintain this repository now, main goal is to offer support to latest wordpress / woocommerce versions.
And of course pull requests are welcome.
